name: test pve
on:
  push:
  
jobs:
  install-pve:
    name: Install PVE
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
                
      - name: Setup PVE
        run: |
            python --version
            python -m venv pve
            source pve/bin/activate
          #pip3 install -r requirements.txt
          #  pip3 list
            python sample.py
      